[k8s-deploy-z4rn1c-1566281392877-b45958599-4sh2g:23519] Warning: could not find environment variable "PS1"
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "athena/horovod_main.py", line 26, in <module>
[1,1]<stderr>:    from athena import BaseSolver
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/__init__.py", line 18, in <module>
[1,1]<stderr>:    from .data import SpeechRecognitionDatasetBuilder
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/__init__.py", line 18, in <module>
[1,1]<stderr>:    from .datasets.speech_recognition import SpeechRecognitionDatasetBuilder
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/datasets/speech_recognition.py", line 22, in <module>
[1,1]<stderr>:    from athena.transform import AudioFeaturizer
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/__init__.py", line 16, in <module>
[1,1]<stderr>:    from athena.transform import audio_featurizer
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/audio_featurizer.py", line 19, in <module>
[1,1]<stderr>:    from athena.transform import feats
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/__init__.py", line 16, in <module>
[1,1]<stderr>:    from athena.transform.feats.read_wav import ReadWav
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/read_wav.py", line 21, in <module>
[1,1]<stderr>:    from athena.transform.feats.ops import py_x_ops
[1,1]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/ops/py_x_ops.py", line 21, in <module>
[1,1]<stderr>:    0
[1,1]<stderr>:IndexError: list index out of range
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "athena/horovod_main.py", line 26, in <module>
[1,0]<stderr>:    from athena import BaseSolver
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/__init__.py", line 18, in <module>
[1,0]<stderr>:    from .data import SpeechRecognitionDatasetBuilder
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/__init__.py", line 18, in <module>
[1,0]<stderr>:    from .datasets.speech_recognition import SpeechRecognitionDatasetBuilder
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/datasets/speech_recognition.py", line 22, in <module>
[1,0]<stderr>:    from athena.transform import AudioFeaturizer
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/__init__.py", line 16, in <module>
[1,0]<stderr>:    from athena.transform import audio_featurizer
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/audio_featurizer.py", line 19, in <module>
[1,0]<stderr>:    from athena.transform import feats
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/__init__.py", line 16, in <module>
[1,0]<stderr>:    from athena.transform.feats.read_wav import ReadWav
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/read_wav.py", line 21, in <module>
[1,0]<stderr>:    from athena.transform.feats.ops import py_x_ops
[1,0]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/ops/py_x_ops.py", line 21, in <module>
[1,0]<stderr>:    0
[1,0]<stderr>:IndexError: list index out of range
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "athena/horovod_main.py", line 26, in <module>
[1,3]<stderr>:    from athena import BaseSolver
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/__init__.py", line 18, in <module>
[1,3]<stderr>:    from .data import SpeechRecognitionDatasetBuilder
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/__init__.py", line 18, in <module>
[1,3]<stderr>:    from .datasets.speech_recognition import SpeechRecognitionDatasetBuilder
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/datasets/speech_recognition.py", line 22, in <module>
[1,3]<stderr>:    from athena.transform import AudioFeaturizer
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/__init__.py", line 16, in <module>
[1,3]<stderr>:    from athena.transform import audio_featurizer
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/audio_featurizer.py", line 19, in <module>
[1,3]<stderr>:    from athena.transform import feats
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/__init__.py", line 16, in <module>
[1,3]<stderr>:    from athena.transform.feats.read_wav import ReadWav
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/read_wav.py", line 21, in <module>
[1,3]<stderr>:    from athena.transform.feats.ops import py_x_ops
[1,3]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/ops/py_x_ops.py", line 21, in <module>
[1,3]<stderr>:    0
[1,3]<stderr>:IndexError: list index out of range
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "athena/horovod_main.py", line 26, in <module>
[1,2]<stderr>:    from athena import BaseSolver
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/__init__.py", line 18, in <module>
[1,2]<stderr>:    from .data import SpeechRecognitionDatasetBuilder
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/__init__.py", line 18, in <module>
[1,2]<stderr>:    from .datasets.speech_recognition import SpeechRecognitionDatasetBuilder
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/data/datasets/speech_recognition.py", line 22, in <module>
[1,2]<stderr>:    from athena.transform import AudioFeaturizer
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/__init__.py", line 16, in <module>
[1,2]<stderr>:    from athena.transform import audio_featurizer
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/audio_featurizer.py", line 19, in <module>
[1,2]<stderr>:    from athena.transform import feats
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/__init__.py", line 16, in <module>
[1,2]<stderr>:    from athena.transform.feats.read_wav import ReadWav
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/read_wav.py", line 21, in <module>
[1,2]<stderr>:    from athena.transform.feats.ops import py_x_ops
[1,2]<stderr>:  File "/nfs/cold_project/sunjianwei/research/github-20200419/fork/athena/athena/transform/feats/ops/py_x_ops.py", line 21, in <module>
[1,2]<stderr>:    0
[1,2]<stderr>:IndexError: list index out of range
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41932,1],1]
  Exit code:    1
--------------------------------------------------------------------------
